{{- if .Values.ambassadorConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "ambassador.fullname" . }}-file-config'
  labels:
    {{- if .Values.legacyLabels }}
    app: {{ include "ambassador.name" . }}
    chart: {{ include "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- else }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
data:
  ambassadorConfig: |-
    {{- .Values.ambassadorConfig | nindent 4 }}
{{- end }}
