{{- if .Values.prometheusExporter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "ambassador.fullname" . }}-exporter-config'
  labels:
    {{- if .Values.legacyLabels }}
    app: {{ include "ambassador.name" . }}
    chart: {{ include "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- else }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
data:
  exporterConfiguration:
{{- if .Values.prometheusExporter.configuration }} |
    {{- .Values.prometheusExporter.configuration | nindent 4 }}
{{- else }} ''
{{- end }}
{{- end }}
