{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ambassador.serviceAccountName" . }}
  labels:
    {{- if .Values.legacyLabels }}
    app: {{ include "ambassador.name" . }}
    chart: {{ include "ambassador.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- else }}
    app.kubernetes.io/name: {{ include "ambassador.name" . }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
{{- end -}}
